apiVersion: v1
kind: Service
metadata:
  name: {{ include "compass-poc.fullname" . }}
  labels:
    {{- include "compass-poc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
{{ toYaml $value | indent 6 }}
  {{- end }}
  selector:
    {{- include "compass-poc.selectorLabels" . | nindent 4 }}
