replicaCount: 1
image:
  repository: dimozone/compass-poc
  pullPolicy: IfNotPresent
  tag: 7562c64
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1001
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - all
env:
  ENVIRONMENT: dev
  PORT: '8888'
  LOG_LEVEL: debug
  SERVICE_NAME: compass-poc
  DIMO_NODE_ENDPOINT: https://dis.dev.dimo.zone/data
  COMPASS_API_KEY: _SCTaBr0CGlrALB_FNnJ1A4Oxr-qA8_AlqKhZI20zNgYjiI=
certificate:
  caConfigMap: cae-dev-dimo-ca-certs
service:
  type: ClusterIP
  ports:
    mon-http:
      port: 8888
      targetPort: mon-http
      protocol: TCP
ports:
  - name: mon-http
    containerPort: 8888
    protocol: TCP
livenessProbe:
  httpGet:
    path: /
    port: mon-http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  httpGet:
    path: /
    port: mon-http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
ingress:
  enabled: false
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: https://compass-poc.dev.dimo.zone, https://app.dev.dimo.zone
    external-dns.alpha.kubernetes.io/hostname: compass-poc.dev.dimo.zone
  hosts:
    - host: compass-poc.dev.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 0
serviceMonitor:
  enabled: true
  path: /metrics
  port: mon-http
  interval: 30s
